name: Run shell comand
on: [push,fork,pull_request]
jobs:
  run-shell-comands:
    runs-on: ubuntu-latest
    steps:
        - name: Echo command
          run: echo "hello  "
        - uses: actions/checkout@master
        - name: RunSnyk to check for vulnerabilities
          uses: snyk/actions/maven@master
          continue-on-error: true
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}