name: OWASP ZAP Integration with GitHub Actions
on: [push]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # escanear el codigo mas reciente de esta accion (zap_scan)
        with:
          ref: master # hacemos referencia a la rama master de esta seccion
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://testphp.vulnweb.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'